let 
	Source = source,
	#"Removed Other Columns0"= Table.SelectColumns(Source, {"39. What type of information would you like to receive to access services?", "39. What type of information would you like to receive to access services?/Health", "39. What type of information would you like to receive to access services?/Legal aid", "39. What type of information would you like to receive to access services?/Food", "39. What type of information would you like to receive to access services?/Livelihoods", "39. What type of information would you like to receive to access services?/Shelter", "39. What type of information would you like to receive to access services?/Return", "39. What type of information would you like to receive to access services?/Protection", "39. What type of information would you like to receive to access services?/Cash", "39. What type of information would you like to receive to access services?/Family reunification", "39. What type of information would you like to receive to access services?/Compensation regarding the mechanism for destroyed houses/apartments", "39. What type of information would you like to receive to access services?/Other", "_index"}),
	#"Remamed Columns1"= Table.RenameColumns(#"Removed Other Columns0", {{"39. What type of information would you like to receive to access services?", "39. What type of information would you like to receive to access services?"},{"39. What type of information would you like to receive to access services?/Health", "Health"},{"39. What type of information would you like to receive to access services?/Legal aid", "Legal aid"},{"39. What type of information would you like to receive to access services?/Food", "Food"},{"39. What type of information would you like to receive to access services?/Livelihoods", "Livelihoods"},{"39. What type of information would you like to receive to access services?/Shelter", "Shelter"},{"39. What type of information would you like to receive to access services?/Return", "Return"},{"39. What type of information would you like to receive to access services?/Protection", "Protection"},{"39. What type of information would you like to receive to access services?/Cash", "Cash"},{"39. What type of information would you like to receive to access services?/Family reunification", "Family reunification"},{"39. What type of information would you like to receive to access services?/Compensation regarding the mechanism for destroyed houses/apartments", "Compensation regarding the mechanism for destroyed houses/apartments"},{"39. What type of information would you like to receive to access services?/Other", "Other"}}),
	#"Remamed Columns2"= Table.RenameColumns(#"Remamed Columns1", {{"39. What type of information would you like to receive to access services?", "Unable/unwilling to answer"}}),
	#"Transformed Columns3"= Table.TransformColumns(#"Remamed Columns2", {"Unable/unwilling to answer", each if _ = null then 1 else 0}),
	#"Unpivoted Columns4"= Table.UnpivotOtherColumns(#"Transformed Columns3", {"_index"}, "Attribute", "Value"),
	#"Filtered Rows5"= Table.SelectRows(#"Unpivoted Columns4", each ([Value] = 1))
in
	#"Filtered Rows5"

