let 
  Source = source,
  #"Removed Other Columns" = Table.SelectColumns(Source,{"18.1.2. What are the factors that make this location feel unsafe?/Armed conflict", "18.1.2. What are the factors that make this location feel unsafe?/Presence of armed actors and/or military", "18.1.2. What are the factors that make this location feel unsafe?/Shelling or threat of shelling", "18.1.2. What are the factors that make this location feel unsafe?/Eviction or threat of eviction", "18.1.2. What are the factors that make this location feel unsafe?/Crime", "18.1.2. What are the factors that make this location feel unsafe?/Tensions with the host community", "18.1.2. What are the factors that make this location feel unsafe?/Threat of GBV, including sexual harrassment and/or exploitation", "18.1.2. What are the factors that make this location feel unsafe?/Presence of hazards, including UXOs", "18.1.2. What are the factors that make this location feel unsafe?/Unsafe or poor living conditions", "18.1.2. What are the factors that make this location feel unsafe?/Don't know", "18.1.2. What are the factors that make this location feel unsafe?/Don't want to say", "18.1.2. What are the factors that make this location feel unsafe?/Other (specify)", "_index"}),
  #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Removed Other Columns", {"_index"}, "18.1.2. What are the factors that make this location feel unsafe?", "Answer"),
  #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "18.1.2. What are the factors that make this location feel unsafe?"}}),
  #"Replaced Value1" = Table.ReplaceValue(#"Renamed Columns","18.1.2. What are the factors that make this location feel unsafe?/Armed conflict","Armed conflict",Replacer.ReplaceText,{"18.1.2. What are the factors that make this location feel unsafe?"}),
  #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","18.1.2. What are the factors that make this location feel unsafe?/Presence of armed actors and/or military","Presence of armed actors and/or military",Replacer.ReplaceText,{"18.1.2. What are the factors that make this location feel unsafe?"}),
  #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","18.1.2. What are the factors that make this location feel unsafe?/Shelling or threat of shelling","Shelling or threat of shelling",Replacer.ReplaceText,{"18.1.2. What are the factors that make this location feel unsafe?"}),
  #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","18.1.2. What are the factors that make this location feel unsafe?/Eviction or threat of eviction","Eviction or threat of eviction",Replacer.ReplaceText,{"18.1.2. What are the factors that make this location feel unsafe?"}),
  #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","18.1.2. What are the factors that make this location feel unsafe?/Crime","Crime",Replacer.ReplaceText,{"18.1.2. What are the factors that make this location feel unsafe?"}),
  #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","18.1.2. What are the factors that make this location feel unsafe?/Tensions with the host community","Tensions with the host community",Replacer.ReplaceText,{"18.1.2. What are the factors that make this location feel unsafe?"}),
  #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","18.1.2. What are the factors that make this location feel unsafe?/Threat of GBV, including sexual harrassment and/or exploitation","Threat of GBV, including sexual harrassment and/or exploitation",Replacer.ReplaceText,{"18.1.2. What are the factors that make this location feel unsafe?"}),
  #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","18.1.2. What are the factors that make this location feel unsafe?/Presence of hazards, including UXOs","Presence of hazards, including UXOs",Replacer.ReplaceText,{"18.1.2. What are the factors that make this location feel unsafe?"}),
  #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","18.1.2. What are the factors that make this location feel unsafe?/Unsafe or poor living conditions","Unsafe or poor living conditions",Replacer.ReplaceText,{"18.1.2. What are the factors that make this location feel unsafe?"}),
  #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","18.1.2. What are the factors that make this location feel unsafe?/Don't know","Don't know",Replacer.ReplaceText,{"18.1.2. What are the factors that make this location feel unsafe?"}),
  #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","18.1.2. What are the factors that make this location feel unsafe?/Don't want to say","Don't want to say",Replacer.ReplaceText,{"18.1.2. What are the factors that make this location feel unsafe?"}),
  #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","18.1.2. What are the factors that make this location feel unsafe?/Other (specify)","Other",Replacer.ReplaceText,{"18.1.2. What are the factors that make this location feel unsafe?"})
in
  #"Replaced Value12"
